apiVersion: skaffold/v2beta29
kind: Config
requires:
  - path: .skaffold/namespaces.yaml
  #- path: .skaffold/secrets.yaml
  #- path: .skaffold/configmaps.yaml
  - path: prefect/dev/skaffold.yaml
  - path: kafka/skaffold.yaml
  - path: kafka-ui/skaffold.yaml