apiVersion: skaffold/v2beta29
kind: Config
metadata:
  name: kafka-ui
requires:
  - path: ../.skaffold/namespaces.yaml
#   - path: secrets.yaml
#   - path: configmaps.yaml
deploy:
  helm:
    releases:
      - name: kafka-ui
        #repo: https://provectus.github.io/kafka-ui-charts
        remoteChart: kafka-ui/kafka-ui
        namespace: playground
        upgradeOnChange: true
        createNamespace: true
        valuesFiles:
         - .helm/values.yaml
portForward:
- resourceType: service
  resourceName: kafka-ui
  namespace: playground
  port: 80
  localPort: 8080