apiVersion: skaffold/v2beta29
kind: Config
metadata:
  name: prefect
requires:
  - path: ../../.skaffold/namespaces.yaml
#   - path: secrets.yaml
#   - path: configmaps.yaml
build:
  artifacts:
    - image: prefect-worker
      context: worker/.docker
      sync:
        infer:
          - '**/*.py'
          - '**/*.yaml'
      docker:
        dockerfile: Dockerfile
    # - image: prefect-server
    #   context: server/.docker
    #   sync:
    #     infer:
    #       - '**/*.py'
    #       - '**/*.yaml'
    #   docker:
    #     dockerfile: Dockerfile
deploy:
  helm:
    releases:
      - name: prefect-server
        repo: https://prefecthq.github.io/prefect-helm
        remoteChart: prefect-server
        namespace: playground
        upgradeOnChange: true
        createNamespace: true
        # valuesFiles:
        #   - server/.helm/values.yaml
        # setValueTemplates:
        #   server.image.repository: "{{.IMAGE_REPO_server}}"
        #   server.image.tag: "{{.IMAGE_TAG_server}}@{{.IMAGE_DIGEST_server}}"
      - name: prefect-worker
        repo: https://prefecthq.github.io/prefect-helm
        remoteChart: prefect-worker
        upgradeOnChange: true
        createNamespace: true
        namespace: playground
        valuesFiles:
          - worker/.helm/values.yaml
        setValueTemplates:
          worker.image.repository: "{{.IMAGE_REPO_prefect_worker}}"
          worker.image.prefectTag: "{{.IMAGE_TAG_prefect_worker}}@{{.IMAGE_DIGEST_prefect_worker}}"
portForward:
- resourceType: service
  resourceName: prefect-server
  namespace: playground
  port: 4200
  localPort: 4200