yamlApplicationConfig:
  kafka:
    clusters:
      - name: yaml
        bootstrapServers:  kafka.playground.svc.cluster.local:9092
        properties:
          security.protocol: SASL_SSL
          sasl.mechanism: SCRAM-SHA-512        
          sasl.jaas.config: org.apache.kafka.common.security.scram.ScramLoginModule required username="admin" password="password";
  auth:
    type: disabled
  management:
    health:
      ldap:
        enabled: false