apiVersion: skaffold/v2beta29
kind: Config
metadata:
  name: kafka
requires:
  - path: ../.skaffold/namespaces.yaml
#   - path: secrets.yaml
#   - path: configmaps.yaml
deploy:
  helm:
    releases:
      - name: kafka
        remoteChart: oci://registry-1.docker.io/bitnamicharts/kafka
        namespace: playground
        upgradeOnChange: true
        createNamespace: true
        valuesFiles:
          - .helm/values.yaml
portForward:
- resourceType: service
  resourceName: kafka
  namespace: playground
  port: 9092
  localPort: 9092